### ISSUE TITLE
hexo generate throwing error after latest commit

### ISSUE THREAD

**Issue by vaibhavbarmy** [invom/Material-T#10]
[3e73a51](https://github.com/invom/Material-T/commit/3e73a51f8391bbe68977c03cd2a0019a77ef2f49)

> ERROR $themes/Material-T/layout/post.ejs:1
 >> 1| <% if(theme.post.toc.enable){ %>
    2| <%     var col_num = 7 %>
    3| <% }else { var col_num = 8 } %>
    4| <div class="row">

Cannot read property 'toc' of undefined
TypeError: $themes/Material-T/layout/post.ejs:1
 >> 1| <% if(theme.post.toc.enable){ %>
    2| <%     var col_num = 7 %>
    3| <% }else { var col_num = 8 } %>
    4| <div class="row">

Cannot read property 'toc' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:9:22)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at route.set ($node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at $node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read ($node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
ERROR $themes/Material-T/layout/post.ejs:1
 >> 1| <% if(theme.post.toc.enable){ %>
    2| <%     var col_num = 7 %>
    3| <% }else { var col_num = 8 } %>
    4| <div class="row">

Cannot read property 'toc' of undefined
TypeError: $themes/Material-T/layout/post.ejs:1
 >> 1| <% if(theme.post.toc.enable){ %>
    2| <%     var col_num = 7 %>
    3| <% }else { var col_num = 8 } %>
    4| <div class="row">

Cannot read property 'toc' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:9:22)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at route.set ($node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at $node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read ($node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
INFO  update Optimize HTML: $themes/Material-T/layout/page.ejs [ 28.84% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/archive.ejs [ 56.53% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/archive.ejs [ 52.20% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/archive.ejs [ 52.20% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/archive.ejs [ 54.99% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/archive.ejs [ 54.99% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/index.ejs [ 43.98% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/archive.ejs [ 54.99% saved]
INFO  update Optimize HTML: $themes/Material-T/layout/_partial/head.ejs [ 13.28% saved]
ERROR $themes/Material-T/layout/layout.ejs:24
    22| 
    23| <body class="<%- body_class %> sidebar-collapse">
 >> 24| <%- partial('_partial/nav') %>
    25|   <div class="page-header header-filter" data-parallax="true" style="background-image: url('<%- head_img %>')">
    26|     <% if(is_post()) { %>
    27|       <div class="container">

$themes/Material-T/layout/_partial/nav.ejs:15
    13|             <div class="collapse navbar-collapse">
    14|                 <ul class="navbar-nav ml-auto">
 >> 15|                     <% if(theme.navbar.menu.enable) { %>
    16|                         <% for(var i in theme.navbar.menu.list) { %>
    17|                             <li class="nav-item">
    18|                                 <a class="nav-link" href="<%- url_for(theme.navbar.menu.list[i]) %>">

Cannot read property 'menu' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:24
    22| 
    23| <body class="<%- body_class %> sidebar-collapse">
 >> 24| <%- partial('_partial/nav') %>
    25|   <div class="page-header header-filter" data-parallax="true" style="background-image: url('<%- head_img %>')">
    26|     <% if(is_post()) { %>
    27|       <div class="container">

$themes/Material-T/layout/_partial/nav.ejs:15
    13|             <div class="collapse navbar-collapse">
    14|                 <ul class="navbar-nav ml-auto">
 >> 15|                     <% if(theme.navbar.menu.enable) { %>
    16|                         <% for(var i in theme.navbar.menu.list) { %>
    17|                             <li class="nav-item">
    18|                                 <a class="nav-link" href="<%- url_for(theme.navbar.menu.list[i]) %>">

Cannot read property 'menu' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:17:24)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] ($node_modules/hexo/lib/theme/view.js:121:22)
    at Theme._View.View.View.renderSync ($node_modules/hexo/lib/theme/view.js:49:23)
    at Object.partial ($node_modules/hexo/lib/plugins/helper/partial.js:38:15)
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:68:17)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
ERROR $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:44:40)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
ERROR $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:44:40)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
ERROR $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:44:40)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
ERROR $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:44:40)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
ERROR $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:44:40)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
ERROR $themes/Material-T/layout/layout.ejs:7
    5| <%    var subtitle = page.title %>
    6| <% } else if(is_home()) { %>
 >> 7| <%    var head_img = theme.index.head_img %>
    8| <%    if(theme.index.subtitle.enable) { var subtitle = config.subtitle } %>
    9| <% } else if (page.type == 'about'){ %>
    10| <%    var head_img = theme.about.head_img || theme.index.head_img %>

Cannot read property 'head_img' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:7
    5| <%    var subtitle = page.title %>
    6| <% } else if(is_home()) { %>
 >> 7| <%    var head_img = theme.index.head_img %>
    8| <%    if(theme.index.subtitle.enable) { var subtitle = config.subtitle } %>
    9| <% } else if (page.type == 'about'){ %>
    10| <%    var head_img = theme.about.head_img || theme.index.head_img %>

Cannot read property 'head_img' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:23:38)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
ERROR $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
TypeError: $themes/Material-T/layout/layout.ejs:14
    12| <%    var body_class = "profile-page" %>
    13| <% } else if(is_archive) { %>
 >> 14| <%    var head_img = theme.archive.head_img || theme.index.head_img %>
    15| <%    var subtitle = 'Archive' %>
    16| <% } else { %>
    17| <%    var subtitle = page.title %>

Cannot read property 'head_img' of undefined
    at eval (eval at compile ($node_modules/ejs/lib/ejs.js:618:12), <anonymous>:44:40)
    at returnedFn ($node_modules/ejs/lib/ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] ($node_modules/hexo/lib/theme/view.js:125:48)
    at Theme._View.View.View.render ($node_modules/hexo/lib/theme/view.js:30:15)
    at _compiled.then.result ($node_modules/hexo/lib/theme/view.js:41:23)
    at tryCatcher ($node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler ($node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise ($node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 ($node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises ($node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep ($node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue ($node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues ($node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] ($node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate (timers.js:632:19)
INFO  0 files generated in 160 ms

**Comment by invom** [comment]
Sorry, the commit tonight has changed a lot to _config.yml. Please regenerate your _config.yml according to the latest configuration file format.

**Comment by vaibhavbarmy** [comment]
Hi, I removed the Material-T folder in themes , then git cloned https://github.com/invom/Material-T/ into themes folder
hexo clean
hexo g
Its not able to compile properly and giving the above error, please check
Thanks

**Comment by invom** [comment]
Hi @vaibhavbarmy ,Last night's push had some problems, [f302c0f](https://github.com/invom/Material-T/commit/f302c0f8a87d5d93c8ae9fb1386cbc93558c83f2) has solved this problem, reconfigure _config.yml file can solve the error, really sorry. :cry:

**Comment by vaibhavbarmy** [comment]
Hi, nothing to be sorry of.
Thanks for sharing this and your timely responses.
I am all set to make blog posts now.
Is there a way I can donate?
One last thing is there a way to add multiple tags to post.md?

嗨，没什么好抱歉的。
感谢您分享此内容并及时回复。
我现在准备发布博客文章了。
有没有办法可以捐赠？
最后一件事是有一种方法可以为post.md添加多个标签吗？
